version: "3"
services:
  gateway-svc:
    image: nginx:latest
    container_name: gateway
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - onedb-net

networks:
  onedb-net:
    name: onedb-net
