name: deploy

on:
  push:
    branches:
      - master
    paths:
      - "docker-compose.yml"
      - "nginx"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            echo '开始执行部署任务'
            rm -rf ~/gh-projects/gateway
            git clone "https://github.com/onedb-document/gateway.git" ~/gh-projects/gateway
            cd ~/gh-projects/gateway
            echo '仓库准备完毕，启动服务'
            docker-compose up -d --pull always
            echo '运行成功'
